[build]
  publish = "dist" # Replace "dist" with your output folder, e.g., "public"
  command = "" # Omit build commands if your site is plain HTML/CSS/JS

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
